### ISSUE TITLE
CancellationTokenRegistration is an IDisposable that should not be disposed

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#29]
Disposing CancellationTokenRegistration  is considered as "unregister the callback" and therefore should not be marked as undisposed
See msdn: https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokenregistration(v=vs.110).aspx

**Comment by BADF00D** [comment]
The [answer from Noseration on stackoverflow](https://stackoverflow.com/questions/21367695/why-cancellationtokenregistration-exists-and-why-does-it-implement-idisposable) convinced me, that the deregistration should part of your cleanup. Otherwise the lifetime your registration is bound to the parent CancellationtokenSource, which might not be under your control. So I will undo this fix.
