### ISSUE TITLE
Recognise use of Reactive CompositeDisposables

### ISSUE THREAD

**Issue by mikesena** [BADF00D/DisposableFixer#49]
ReactiveX offers the structures, `CompositeDisposable` and `StableCompositeDisposable` to help handle reactive streams that create multiple disposables.

Is it possible to support these disposable 'containers'?

**Comment by BADF00D** [comment]
The `CompositeDisposable `is already recognized correctly and `StableCompositeDisposable` should be too, beside I don't know the second one. I just lookup up the [code](https://github.com/Reactive-Extensions/Rx.NET/tree/develop/Rx.NET/Source/src/System.Reactive/Disposables) and they both implement `IDisposable ` (directly or via `ICancelable`).

The real problem is, the extension method `AddTo<T>(this ICollection<IDisposable>, T) where T : IDisposable`. I already work on this feature in #34. But this is complicated to detect, so I will need some time to figure this out.

**Comment by BADF00D** [comment]
Fixed in version 0.26.0.0
